version: '3.3'
services:
 db:
  image: mysql:5.7
  container_name: mysql_tainacan_benchmark
  ports:
    - "3306"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: tainacan
    MYSQL_DATABASE: tainacan
    MYSQL_USER: root
    MYSQL_PASSWORD: tainacan
  volumes:
  - ./data:/var/lib/mysql
  - ./docker/init.d:/docker-entrypoint-initdb.d

 wordpress:
  build:
    context: .
    dockerfile: ./docker/Dockerfile
  container_name: wordpress_tainacan_benchmark
  ports:
     - "80:80"
     - "25"
  restart: always
  environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: tainacan
    WORDPRESS_DB: tainacan
    DB_HOST: db
  depends_on:
     - db
  volumes:
   - ./script:/script

 elasticsearch: #before execute sudo sysctl -w vm.max_map_count=262144
  image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
  container_name: elasticsearch_benchmark
  environment:
    - node.name=es01
    - cluster.name=docker-cluster-es
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    nproc: 65535
    memlock:
      soft: -1
      hard: -1
  cap_add:
    - ALL
  privileged: true
  volumes:
    - esdata:/usr/share/elasticsearch/data
  ports:
    - 9200:9200
    - 9300:9300
volumes:
  esdata:
