version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql_tainacan
    ports:
    - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tainacan
      MYSQL_DATABASE: tainacan
      MYSQL_USER: tainacan
      MYSQL_PASSWORD: tainacan
    volumes:
    - ./data:/var/lib/mysql
    - ./docker/init.d:/docker-entrypoint-initdb.d
  wordpress:
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
    container_name: tainacan-dev
    ports:
    - "80:80"
    - "25"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: tainacan
      WORDPRESS_DB_PASSWORD: tainacan
      WORDPRESS_DB: tainacan
      WORDPRESS_DB_TEST: tainacan_test
      WORDPRESS_PATH_TEST: /tainacan_test
    depends_on:
    - db
    volumes:
    - ./src:/src
    - ./conf/wp/bootstrap-config.php:/src/tainacan/tests/bootstrap-config.php
    - ./conf/tainacan/plugin_build-config.cfg:/src/tainacan/build-config.cfg
    - ./conf/tainacan/theme_build-config.cfg:/src/tainacan-theme/build-config.cfg
    - ./conf/scripts/build_theme.sh:/src/build_theme.sh
    - ./conf/scripts/build_plugin.sh:/src/build_plugin.sh
    - ./conf/scripts/run_tests.sh /src/run_tests.sh
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - type: volume
      source: www_data
      target: /var/www/html
      volume:
        nocopy: false

volumes:
  www_data:
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_PATH}${WEB_APP_PATH}
      o: bind
