version: '3.3'
services:
 db:
  image: mysql:5.7
  container_name: mysql_tainacan
  ports:
    - "3306"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: tainacan
    MYSQL_DATABASE: tainacan
    MYSQL_USER: tainacan
    MYSQL_PASSWORD: tainacan
  volumes:
  - ./data:/var/lib/mysql
  - ./docker/init.d:/docker-entrypoint-initdb.d
 wordpress:
  build:
    context: .
    dockerfile: ./docker/Dockerfile
  container_name: wordpress_tainacan
  ports:
     - "80:80"
     - "25"
  restart: always
  environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_USER: tainacan
    WORDPRESS_DB_PASSWORD: tainacan
    WORDPRESS_DB: tainacan
    WORDPRESS_DB_TEST: tainacan_test
    WORDPRESS_PATH_TEST: /tainacan_test
  depends_on:
     - db
  volumes:
   - ./repo:/repo
   - ./wp-content:/var/www/html/wp-content
   - /etc/timezone:/etc/timezone:ro
   - /etc/localtime:/etc/localtime:ro
 elasticsearch: #before execute sudo sysctl -w vm.max_map_count=262144
  image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
  container_name: elasticsearch
  environment:
    - node.name=es01
    - cluster.name=docker-cluster-es
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    nproc: 65535
    memlock:
      soft: -1
      hard: -1
  cap_add:
    - ALL
  privileged: true
  volumes:
    - esdata:/usr/share/elasticsearch/data
    #-  ./elasticsearch/custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    -  ./elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
  ports:
    - 9200:9200
    - 9300:9300
# kibana:
#   image: docker.elastic.co/kibana/kibana-oss:6.3.0
#   container_name: kibana
#   environment:
#     SERVER_NAME: localhost
#     ELASTICSEARCH_URL: http://elasticsearch:9200/
#   ports:
#     - 5601:5601
#   ulimits:
#     nproc: 65535
#     memlock:
#       soft: -1
#       hard: -1
#   cap_add:
#     - ALL     
volumes:
  esdata:
