version: '3.3'
services:
 db:
   image: mysql:5.7
   container_name: mysql_tainacan
   ports:
     - "3306"
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: tainacan
     MYSQL_DATABASE: tainacan
     MYSQL_USER: tainacan
     MYSQL_PASSWORD: tainacan
   volumes:
   - ./data:/var/lib/mysql
   - ./docker/init.d:/docker-entrypoint-initdb.d
 wordpress:
  build:
    context: .
    dockerfile: ./docker/Dockerfile
  container_name: wordpress_tainacan
  ports:
     - "3002:80"
     - "25"
  restart: always
  environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_USER: tainacan
    WORDPRESS_DB_PASSWORD: tainacan
    WORDPRESS_DB: tainacan
    WORDPRESS_DB_TEST: tainacan_test
    WORDPRESS_PATH_TEST: /tainacan_test
  depends_on:
     - db
  volumes:
   - ./repo:/repo
