version: '3.3'
services:
 tainacan:
  build:
    context: .
    dockerfile: ./Dockerfile
  container_name: wordpress_tainacan
  ports:
     - "80:80"
  environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_USER: tainacan
    WORDPRESS_DB_PASSWORD: tainacan
    WORDPRESS_DB_NAME: tainacan
  volumes:
   - ./volumes/themes:/var/www/html/wp-content/themes/
   - ./volumes/plugins:/var/www/html/wp-content/plugins/
   - ./volumes/uploads:/var/www/html/wp-content/uploads/
   - wp_root:/var/www/html

 db:
  image: mysql:5.7
  container_name: tainacan_db
  ports:
    - "3306"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: tainacan
    MYSQL_DATABASE: tainacan
    MYSQL_USER: tainacan
    MYSQL_PASSWORD: tainacan
  volumes:
  - ./data:/var/lib/mysql

volumes:
  wp_root:
